name: muscletrack_t2d
description: Simple workout logging, training calendar and strength progress tracking.
publish_to: 'none'
version: 0.3.0+10

environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.3
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
